---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by>=1"
      - "check-success=Semantic Pull Request"
      - "check-success=symplegma-containerd:linter"
      - "check-success=symplegma-containerd:molecule"
    actions:
      merge:
        method: squash
